#!/usr/bin/env python
import sys
from twython import Twython

consumerKey = 'pZq6xYSByzpDF9YnbiOoB0bcp'  
consumerSecret= 'Y4loC8w1yQPIf4mZ7X5zHNmMfc6DG6YLU1QTYusypTfhZ4KXZS'
accessKey= '1060151021962477569-9Bb5SiPWOnEJuOkMRbNfa08lCXVdMA'
accessSecret = 'gKWnozDlYIzKtHi6jxU2sMwOT41PU5iGuRd7ojBQN7p9X'
api = Twython(consumerKey,consumerSecret,accessKey,accessSecret) 
api.update_status(status=sys.argv)

tweet = "Hello"
status = api.update_status(status=tweet) 
