#!/usr/bin/env python
import sys
from twython import Twython

#ide jönnek a kulcsok
api = Twython(consumerKey,consumerSecret,accessKey,accessSecret) 
api.update_status(status=sys.argv)

tweet = "Hello"
status = api.update_status(status=tweet) 
